<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Lands extends \App\Entity\Lands implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'percentage', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'x', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'y', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'ships', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'wars'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'percentage', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'x', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'y', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'ships', '' . "\0" . 'App\\Entity\\Lands' . "\0" . 'wars'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Lands $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercentage(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercentage', []);

        return parent::getPercentage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercentage(int $percentage): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercentage', [$percentage]);

        return parent::setPercentage($percentage);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getX(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getX', []);

        return parent::getX();
    }

    /**
     * {@inheritDoc}
     */
    public function setX(int $x): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setX', [$x]);

        return parent::setX($x);
    }

    /**
     * {@inheritDoc}
     */
    public function getY(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getY', []);

        return parent::getY();
    }

    /**
     * {@inheritDoc}
     */
    public function setY(int $y): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setY', [$y]);

        return parent::setY($y);
    }

    /**
     * {@inheritDoc}
     */
    public function getShips(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShips', []);

        return parent::getShips();
    }

    /**
     * {@inheritDoc}
     */
    public function addShip(\App\Entity\Ship $ship): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShip', [$ship]);

        return parent::addShip($ship);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShip(\App\Entity\Ship $ship): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShip', [$ship]);

        return parent::removeShip($ship);
    }

    /**
     * {@inheritDoc}
     */
    public function getWars(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWars', []);

        return parent::getWars();
    }

    /**
     * {@inheritDoc}
     */
    public function addWar(\App\Entity\War $war): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addWar', [$war]);

        return parent::addWar($war);
    }

    /**
     * {@inheritDoc}
     */
    public function removeWar(\App\Entity\War $war): \App\Entity\Lands
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeWar', [$war]);

        return parent::removeWar($war);
    }

}
