<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCxmgcF3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCxmgcF3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCxmgcF3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCxmgcF3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCxmgcF3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CxmgcF3',
    'container.build_id' => '2f8423fc',
    'container.build_time' => 1596890546,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCxmgcF3');
